version: '3.3'

networks:
  entropia:
    driver: bridge

services:
  secure:
    image: nginx:latest
    container_name: nginx
    networks:
      - entropia
    expose:
      - 80
    ports:
      - ${PORT}:80
    #  - 80:80
    restart: unless-stopped
    volumes:
    # /opt/web/authelia/compose/lite/nginx/
    # /opt/web/site
      - "${CONFIG_PATH}/.htpasswd:/etc/nginx/.htpasswd:ro"
      - "${SITE_PATH}:/var/www/html"
      - "${CONFIG_PATH}:/etc/nginx"
